insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`, `job`) values (1, 'Justin', 1990, 5, 1, 'Programmer');
insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values (2, 'David', 1990, 7, 1);
insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values (3, 'Dennis', 1990, 3, 1);
insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values (4, 'Sophia', 1990, 2, 1);
insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values (5, 'Benny', 1993, 1, 1);
insert into person(`id`, `name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`, `job`, `hobby`, `phone_number`, `address`) values (6, 'Tony', 1991, 7, 10, 'Officer', 'Reading', '010-1234-5678', 'Seoul');
insert into person(`id`, `name`, `deleted`) values (7, 'Andrew', true);
--6월달만 만들겠습니다
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude01', 1993, 6, 1);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude02', 1993, 6, 2);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude03', 1993, 6, 3);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude04', 1993, 6, 4);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude05', 1993, 6, 5);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude06', 1993, 6, 6);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude07', 1993, 6, 7);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude08', 1993, 6, 8);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude09', 1993, 6, 9);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude10', 1993, 6, 10);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude11', 1993, 6, 11);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude12', 1993, 6, 12);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude13', 1993, 6, 13);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude14', 1993, 6, 14);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude15', 1993, 6, 15);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude16', 1993, 6, 16);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude17', 1993, 6, 17);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude18', 1993, 6, 18);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude19', 1993, 6, 19);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude20', 1993, 6, 20);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude21', 1993, 6, 21);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude22', 1993, 6, 22);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude23', 1993, 6, 23);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude24', 1993, 6, 24);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude25', 1993, 6, 25);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude26', 1993, 6, 26);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude27', 1993, 6, 27);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude28', 1993, 6, 28);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude29', 1993, 6, 29);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude30', 1993, 6, 30);
insert into person(`name`, `year_of_birthday`, `month_of_birthday`, `day_of_birthday`) values ('Random Dude31', 1993, 7, 1);
